'use client';
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api, PlanCreate } from '@/lib/api';
import { PlanForm } from '@/components/plans/PlanForm';
import { PlanList } from '@/components/plans/PlanList';
import { PlanDetail } from '@/components/plans/PlanDetail';
import { useWebSocketInvalidation } from '@/lib/useWebSocket';

export default function PlansPage() {
  const [selectedPlanId, setSelectedPlanId] = useState<string | null>(null);
  const qc = useQueryClient();
  const { data: plans = [], isLoading, isError, error } = useQuery({ queryKey: ['plans'], queryFn: () => api.listPlans() });
  const createMut = useMutation({ mutationFn: (input: PlanCreate) => api.createPlan(input), onSuccess: () => qc.invalidateQueries({ queryKey: ['plans'] }) });
  useWebSocketInvalidation('plans', ['plans', 'plan']);
  return <div className="mx-auto max-w-[1320px] space-y-8"><header className="flex items-end justify-between gap-6 border-b border-slate-800 pb-7"><div><p className="text-xs font-semibold tracking-[.14em] text-blue-400">TRADE WORKBENCH</p><h1 className="mt-2 text-4xl font-semibold tracking-tight text-slate-50">交易计划</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">以可复核的方式管理每一次入场、风险边界与执行条件。创建计划不会直接向交易所下单。</p></div><div className="hidden text-right text-xs text-slate-500 lg:block"><p>所有数值均须通过风险校验</p><p className="mt-1 text-emerald-400">● 当前为模拟决策流程</p></div></header><div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.08fr)_minmax(360px,.72fr)]"><div className="rounded-xl border border-slate-800 bg-slate-900/65 p-6 shadow-[0_24px_70px_rgba(0,0,0,.16)]"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-lg font-semibold text-slate-100">新建交易计划</h2><p className="mt-1 text-xs text-slate-500">填写完成后进入可执行性与风险校验。</p></div><span className="rounded-full border border-blue-400/20 bg-blue-400/10 px-3 py-1 text-xs font-medium text-blue-300">草稿</span></div><PlanForm onSubmit={(value)=>createMut.mutate(value)} submitting={createMut.isPending} /></div><aside className="space-y-5">{selectedPlanId?<div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900/65"><PlanDetail planId={selectedPlanId}/></div>:<PlanReadiness/>}<section className="rounded-xl border border-slate-800 bg-slate-900/45 p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-100">已保存计划</h2><span className="text-xs text-slate-500">{plans.length} 个</span></div>{isError&&<p className="mt-3 text-sm text-rose-300">加载失败：{(error as Error).message}</p>}<div className="mt-3"><PlanList plans={plans} loading={isLoading} onSelect={setSelectedPlanId} selectedId={selectedPlanId}/></div></section></aside></div></div>;
}

function PlanReadiness(){return <section className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900/65"><div className="border-b border-slate-800 px-5 py-4"><p className="text-xs font-semibold tracking-[.12em] text-blue-400">PLAN READINESS</p><h2 className="mt-2 text-lg font-semibold text-slate-100">决策准备度</h2><p className="mt-1 text-sm leading-6 text-slate-500">完成左侧计划后，这里会生成可执行性与风险摘要。</p></div><div className="space-y-4 px-5 py-5"><Check label="市场与方向" detail="交易对和方向已定义" state="待填写"/><Check label="入场与退出" detail="止损、止盈决定风险边界" state="待校验"/><Check label="仓位与风险" detail="杠杆和账户权益用于仓位计算" state="待校验"/></div><div className="border-t border-slate-800 bg-slate-950/25 px-5 py-4"><p className="text-xs leading-5 text-slate-500">提示：计划提交后仍需经过风控、确认与执行监控，避免把“创建计划”误认为下单。</p></div></section>;}
function Check({label,detail,state}:{label:string;detail:string;state:string}){return <div className="flex gap-3"><span className="mt-1 h-2.5 w-2.5 rounded-full border border-slate-600 bg-slate-800"/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-slate-200">{label}</p><span className="text-[11px] text-slate-500">{state}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div></div>;}
