/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Kill Switch */
        post: operations["toggle_kill_switch_api_system_kill_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/execution-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Execution Mode */
        post: operations["toggle_execution_mode_api_system_execution_mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Configs */
        get: operations["get_active_configs_api_configs_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Configs */
        get: operations["list_configs_api_configs_get"];
        put?: never;
        /** Create Config */
        post: operations["create_config_api_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/configs/{version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Config */
        post: operations["activate_config_api_configs__version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_trade_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_trade_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade-plans/{plan_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Plan */
        post: operations["check_plan_api_trade_plans__plan_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade-plans/{plan_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Plan */
        post: operations["execute_plan_api_trade_plans__plan_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade-plans/{plan_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Order Status */
        post: operations["sync_order_status_api_trade_plans__plan_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade-plans/{plan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Plan Order */
        post: operations["cancel_plan_order_api_trade_plans__plan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade-plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_trade_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/calculate-position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Position Endpoint */
        post: operations["calculate_position_endpoint_api_risk_calculate_position_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Risk Check Endpoint */
        post: operations["risk_check_endpoint_api_risk_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/ticker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticker */
        get: operations["get_ticker_api_market_ticker_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/klines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Klines */
        get: operations["get_klines_api_market_klines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/orderbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orderbook */
        get: operations["get_orderbook_api_market_orderbook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Journals */
        get: operations["list_journals_api_journals_get"];
        put?: never;
        /** Create Journal */
        post: operations["create_journal_api_journals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journals/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Journal Summary */
        get: operations["get_journal_summary_api_journals_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journals/{journal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Journal */
        get: operations["get_journal_api_journals__journal_id__get"];
        /** Update Journal */
        put: operations["update_journal_api_journals__journal_id__put"];
        post?: never;
        /** Delete Journal */
        delete: operations["delete_journal_api_journals__journal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluate Opportunity */
        get: operations["evaluate_opportunity_api_ai_evaluate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIEvaluationResult */
        AIEvaluationResult: {
            /** Symbol */
            symbol: string;
            /** Direction */
            direction: string;
            /** Overall Score */
            overall_score: string;
            grade: components["schemas"]["EvaluationGrade"];
            /** Recommendation */
            recommendation: string;
            /** Signals */
            signals: components["schemas"]["IndicatorResult"][];
            /** Summary */
            summary: string;
            /** Risk Level */
            risk_level: string;
            /** Conviction */
            conviction: string;
        };
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** ApiResponse[AIEvaluationResult] */
        ApiResponse_AIEvaluationResult_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["AIEvaluationResult"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
        };
        /** CalculatePositionRequest */
        CalculatePositionRequest: {
            /** Equity */
            equity: number | string;
            /** Risk Percent */
            risk_percent: number | string;
            /** Entry Price */
            entry_price: number | string;
            /** Stop Loss Price */
            stop_loss_price?: number | string | null;
            /** Take Profit Prices */
            take_profit_prices?: (number | string)[];
            /** Leverage */
            leverage: number | string;
            /** Fee Rate */
            fee_rate: number | string;
            direction: components["schemas"]["Direction"];
            /** Symbol */
            symbol: string;
        };
        /** CreateConfigRequest */
        CreateConfigRequest: {
            /** Config Type */
            config_type: string;
            /** Version Label */
            version_label: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "LONG" | "SHORT";
        /**
         * EvaluationGrade
         * @enum {string}
         */
        EvaluationGrade: "A" | "B" | "C" | "D" | "F";
        /** ExecutionModeRequest */
        ExecutionModeRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndicatorResult */
        IndicatorResult: {
            /** Name */
            name: string;
            /** Value */
            value?: string | null;
            signal: components["schemas"]["SignalType"];
            /** Weight */
            weight: string;
            /** Score */
            score: string;
            /** Explanation */
            explanation: string;
        };
        /** KillSwitchRequest */
        KillSwitchRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * KlineInterval
         * @enum {string}
         */
        KlineInterval: "1m" | "5m" | "15m" | "30m" | "1h" | "4h" | "6h" | "12h" | "1d" | "1w";
        /**
         * MarginMode
         * @enum {string}
         */
        MarginMode: "isolated" | "crossed";
        /**
         * OpportunityGrade
         * @enum {string}
         */
        OpportunityGrade: "A" | "B" | "C" | "BLOCKED";
        /** PositionSizingOut */
        PositionSizingOut: {
            /** Id */
            id?: string | null;
            /** Trade Plan Id */
            trade_plan_id?: string | null;
            /** Equity */
            equity: number | string;
            /** Risk Percent */
            risk_percent: number | string;
            /** Risk Amount */
            risk_amount: number | string;
            /** Entry Price */
            entry_price: number | string;
            /** Stop Loss Price */
            stop_loss_price?: number | string | null;
            /** Stop Distance Percent */
            stop_distance_percent: number | string;
            /** Notional Value */
            notional_value: number | string;
            /** Raw Size */
            raw_size: number | string;
            /** Rounded Size */
            rounded_size?: number | string | null;
            /** Required Margin */
            required_margin: number | string;
            /** Leverage */
            leverage: number | string;
            /** Estimated Fee */
            estimated_fee: number | string;
            /** Risk Reward Ratio */
            risk_reward_ratio: number | string;
            /** Estimated Loss At Stop */
            estimated_loss_at_stop: number | string;
            /** Sizing Warnings */
            sizing_warnings?: string[];
        };
        /** RiskCheckRequest */
        RiskCheckRequest: {
            plan: components["schemas"]["TradePlanCreate"];
            sizing_result: components["schemas"]["PositionSizingOut"];
        };
        /**
         * SignalType
         * @enum {string}
         */
        SignalType: "strong_buy" | "buy" | "neutral" | "sell" | "strong_sell";
        /** TradeJournalCreate */
        TradeJournalCreate: {
            /** Trade Plan Id */
            trade_plan_id?: string | null;
            /**
             * Exchange
             * @default bitget
             */
            exchange: string;
            /** Symbol */
            symbol: string;
            /** Direction */
            direction: string;
            /** Entry Price */
            entry_price: number | string;
            /** Exit Price */
            exit_price?: number | string | null;
            /** Quantity */
            quantity: number | string;
            /**
             * Leverage
             * @default 1
             */
            leverage: number | string;
            /** Pnl */
            pnl?: number | string | null;
            /** Pnl Percent */
            pnl_percent?: number | string | null;
            /** Setup Type */
            setup_type?: string | null;
            /** Entry Reason */
            entry_reason?: string | null;
            /** Exit Reason */
            exit_reason?: string | null;
            /** Lessons Learned */
            lessons_learned?: string | null;
            /** Emotions */
            emotions?: string | null;
            /**
             * Status
             * @default OPEN
             */
            status: string;
            /** Entry At */
            entry_at?: string | null;
            /** Exit At */
            exit_at?: string | null;
        };
        /** TradeJournalUpdate */
        TradeJournalUpdate: {
            /** Exit Price */
            exit_price?: number | string | null;
            /** Pnl */
            pnl?: number | string | null;
            /** Pnl Percent */
            pnl_percent?: number | string | null;
            /** Exit Reason */
            exit_reason?: string | null;
            /** Lessons Learned */
            lessons_learned?: string | null;
            /** Emotions */
            emotions?: string | null;
            /** Status */
            status?: string | null;
            /** Exit At */
            exit_at?: string | null;
        };
        /** TradePlanCreate */
        TradePlanCreate: {
            /**
             * Exchange
             * @default bitget
             */
            exchange: string;
            /** Symbol */
            symbol: string;
            direction: components["schemas"]["Direction"];
            /** Entry Price */
            entry_price: number | string;
            /** Stop Loss Price */
            stop_loss_price?: number | string | null;
            /** Take Profit Prices */
            take_profit_prices?: (number | string)[];
            /** Leverage */
            leverage: number | string;
            /** Risk Percent */
            risk_percent: number | string;
            opportunity_grade: components["schemas"]["OpportunityGrade"];
            /** Equity */
            equity: number | string;
            /** Setup Type */
            setup_type?: string | null;
            /** @default isolated */
            margin_mode: components["schemas"]["MarginMode"];
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_api_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    toggle_kill_switch_api_system_kill_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_execution_mode_api_system_execution_mode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionModeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_configs_api_configs_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_configs_api_configs_get: {
        parameters: {
            query: {
                /** @description 配置类型: risk/execution/opportunity_grade/symbol_rules */
                type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_config_api_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_config_api_configs__version_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_trade_plans_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_trade_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradePlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_plan_api_trade_plans__plan_id__check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_plan_api_trade_plans__plan_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_order_status_api_trade_plans__plan_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_plan_order_api_trade_plans__plan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_trade_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_position_endpoint_api_risk_calculate_position_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculatePositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_check_endpoint_api_risk_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticker_api_market_ticker_get: {
        parameters: {
            query: {
                /** @description 交易对，如 BTCUSDT */
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_klines_api_market_klines_get: {
        parameters: {
            query: {
                /** @description 交易对，如 BTCUSDT */
                symbol: string;
                /** @description K线周期 */
                interval?: components["schemas"]["KlineInterval"];
                /** @description 返回数量 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orderbook_api_market_orderbook_get: {
        parameters: {
            query: {
                /** @description 交易对，如 BTCUSDT */
                symbol: string;
                /** @description 档位数量 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_journals_api_journals_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                symbol?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_journal_api_journals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeJournalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_journal_summary_api_journals_summary_get: {
        parameters: {
            query?: {
                symbol?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_journal_api_journals__journal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_journal_api_journals__journal_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeJournalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_journal_api_journals__journal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                journal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_opportunity_api_ai_evaluate_get: {
        parameters: {
            query: {
                /** @description 交易对，如 BTCUSDT */
                symbol: string;
                /** @description 方向: LONG 或 SHORT */
                direction: components["schemas"]["Direction"];
                /** @description 入场价格 */
                entry_price: number | string;
                /** @description K线周期 */
                interval?: components["schemas"]["KlineInterval"];
                /** @description K线数量 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AIEvaluationResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
