"""init v0.1 tables

Revision ID: e465fb3ecf35
Revises: 
Create Date: 2026-07-07 22:25:51.478101

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e465fb3ecf35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_risk_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_loss_r', sa.Numeric(), nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_trade_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_type', sa.String(length=32), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_type', 'version_label', name='uq_config_versions_type_label')
    )
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_plan_id', sa.UUID(), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('setup_type', sa.String(length=64), nullable=True),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('stop_loss_price', sa.Numeric(), nullable=True),
    sa.Column('take_profit_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('leverage', sa.Numeric(), nullable=False),
    sa.Column('margin_mode', sa.String(length=32), nullable=False),
    sa.Column('risk_percent', sa.Numeric(), nullable=False),
    sa.Column('opportunity_grade', sa.String(length=16), nullable=False),
    sa.Column('equity', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('risk_config_version', sa.String(length=64), nullable=True),
    sa.Column('strategy_config_version', sa.String(length=64), nullable=True),
    sa.Column('user_trading_config_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_enabled', sa.Boolean(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('account_equity', sa.Numeric(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_sizing_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_plan_id', sa.UUID(), nullable=True),
    sa.Column('equity', sa.Numeric(), nullable=False),
    sa.Column('risk_percent', sa.Numeric(), nullable=False),
    sa.Column('risk_amount', sa.Numeric(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('stop_loss_price', sa.Numeric(), nullable=True),
    sa.Column('stop_distance_percent', sa.Numeric(), nullable=False),
    sa.Column('notional_value', sa.Numeric(), nullable=False),
    sa.Column('raw_size', sa.Numeric(), nullable=False),
    sa.Column('rounded_size', sa.Numeric(), nullable=True),
    sa.Column('required_margin', sa.Numeric(), nullable=False),
    sa.Column('leverage', sa.Numeric(), nullable=False),
    sa.Column('estimated_fee', sa.Numeric(), nullable=False),
    sa.Column('risk_reward_ratio', sa.Numeric(), nullable=False),
    sa.Column('estimated_loss_at_stop', sa.Numeric(), nullable=False),
    sa.Column('sizing_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_plan_id'], ['trade_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_amount', sa.Numeric(), nullable=False),
    sa.Column('notional_value', sa.Numeric(), nullable=False),
    sa.Column('required_margin', sa.Numeric(), nullable=False),
    sa.Column('risk_reward_ratio', sa.Numeric(), nullable=False),
    sa.Column('max_allowed_risk_percent', sa.Numeric(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_config_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_plan_id'], ['trade_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_gate_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_plan_id', sa.UUID(), nullable=True),
    sa.Column('risk_check_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_check_id'], ['risk_checks.id'], ),
    sa.ForeignKeyConstraint(['trade_plan_id'], ['trade_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        "idx_config_versions_active",
        "config_versions",
        ["config_type"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_config_versions_active", table_name="config_versions")
    op.drop_table('decision_gate_results')
    op.drop_table('risk_checks')
    op.drop_table('position_sizing_results')
    op.drop_table('user_settings')
    op.drop_table('trade_plans')
    op.drop_table('system_events')
    op.drop_table('config_versions')
    op.drop_table('account_risk_states')
    # ### end Alembic commands ###